'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const stock = fs.readFileSync(path.join(root, 'js', 'stock.js'), 'utf8');
const history = fs.readFileSync(path.join(root, 'js', 'yt-clicks.js'), 'utf8');
const calendar = fs.readFileSync(path.join(root, 'schedule', 'js', 'app.js'), 'utf8');
const ps = stock.indexOf('    var applyPreview = function (prevB) {');
const pe = stock.indexOf('\n    };', ps) + 7;
const ap = stock.slice(ps, pe);
const hs = stock.indexOf('  function persistHistoryPreview_(meta, blobHint) {');
const he = stock.indexOf('  function toBlobSafe_(', hs);
const historyPersist = stock.slice(hs, he);
assert(ps >= 0 && pe > ps, 'extract applyPreview');
assert(hs >= 0 && he > hs, 'extract common history preview persistence');
assert(ap.includes('return persistHistoryPreview_(meta, prevB);'), 'all preview writers use one persistence path');
assert(historyPersist.includes('blobToDataUrlP_(blob)'), 'await blob conversion');
assert(historyPersist.includes('return usedImagesSave_('), 'await durable used-image save');
assert(stock.includes('_draftHistoryPreviewReady[id] = persistHistoryPreview_(meta, prevBlob);'), 'draft creation commits history preview before Drive');
assert(stock.includes('return applyPreview(prevB).then(function () { return prevB; });'), 'previewReady awaits history commit');
assert(stock.includes("new CustomEvent('go5-used-images-updated'"), 'emit committed event');
assert(history.includes("document.addEventListener('go5-used-images-updated'"), 'patch history on commit');
const la = stock.indexOf("store.get('stock_prev_' + id)");
const ua = stock.indexOf('return usedPrevBlob_();', la);
const da = stock.indexOf("readDriveAsset_('fetchPreview')", la);
assert(la >= 0 && ua > la && da > ua, 'prefer local history image before Drive');
assert(stock.includes('Go5Sync.fetchBlobR2At(PREVNAME(id), 12000)'), 'bounded direct R2 preview');
const ma = calendar.indexOf('  function onDayPosts');
const aa = calendar.indexOf('  function applyLink(', ma);
const mb = calendar.slice(ma, aa);
assert(!/if \(auto[^\n]+applyLink/.test(mb), 'opening modal cannot auto-apply');
assert(mb.includes('btn.onclick = function ()'), 'explicit button commits');
console.log('regen preview commit / calendar click guard tests: ok');
